name: escuela
channels:
  - conda-forge
  - defaults
dependencies:
  # :thinking:
  #- jupyterhub-singleuser>=3.0,<4.0
  # Install packages from pip
  - pip

  - python=3.12
  - torchgeo
  - gdown
  - opencv
  - ipython
  - ipykernel
  - fastparquet
  - scikit-learn
  - tensorflow-gpu
  - pydot
  - rasterio
